export const FETCH_TOP_DOWNLOADS        = 'FETCH_TOP_DOWNLOADS'
export const FETCH_TOP_FINISHED         = 'FETCH_TOP_FINISHED'
export const FETCH_NEW                  = 'FETCH_NEW'
export const FETCH_LOCAL_SONGS          = 'FETCH_LOCAL_SONGS'
export const FETCH_LOCAL_PLAYLISTS      = 'FETCH_LOCAL_PLAYLISTS'
export const REFRESH                    = 'REFRESH'
export const LOAD_MORE                  = 'LOAD_MORE'
export const ADD_BSABER_RATING          = 'ADD_BSABER_RATING'
export const SET_SCROLLTOP              = 'SET_SCROLLTOP'
export const SET_DOWNLOADING_COUNT      = 'SET_DOWNLOADING_COUNT'
export const SET_WAIT_LIST              = 'EST_WAIT_LIST'

export const LOAD_NEW_PLAYLIST_IMAGE    = 'LOAD_NEW_PLAYLIST_IMAGE'
export const CREATE_NEW_PLAYLIST        = 'CREATE_NEW_PLAYLIST'
export const DELETE_PLAYLIST            = 'DELETE_PLAYLIST'
export const SET_NEW_PLAYLIST_OPEN      = 'SET_NEW_PLAYLIST_OPEN'
export const SET_PLAYLIST_PICKER_OPEN   = 'SET_PLAYLIST_PICKER_OPEN'
export const CLEAR_PLAYLIST_DIALOG      = 'CLEAR_PLAYLIST_DIALOG'
export const LOAD_PLAYLIST_DETAILS      = 'LOAD_PLAYLIST_DETAILS'
export const LOAD_PLAYLIST_SONGS        = 'LOAD_PLAYLIST_SONGS'
export const CLEAR_PLAYLIST_DETAILS     = 'CLEAR_PLAYLIST_DETAILS'
export const SET_PLAYLIST_EDITING       = 'SET_PLAYLIST_EDITING'

export const DISPLAY_WARNING            = 'DISPLAY_WARNING'
export const REMOVE_WARNING             = 'REMOVE_WARNING'
export const CLEAR_WARNINGS             = 'CLEAR_WARNINGS'

export const SET_SOURCE                 = 'SET_SOURCE'
export const SET_RESOURCE               = 'SET_RESOURCE'
export const SET_RESOURCE_URL           = 'SET_RESOURCE_URL'

export const SET_VIEW                   = 'SET_VIEW'
export const SET_SONG_VIEW              = 'SET_SONG_VIEW'

export const SET_LOADING                = 'SET_LOADING'
export const SET_LOADING_MORE           = 'SET_LOADING_MORE'

export const RESIZE_WINDOW              = 'RESIZE_WINDOW'
export const RESIZE_SIDEBAR             = 'RESIZE_SIDEBAR'

export const SET_SETTINGS_OPEN          = 'SET_SETTINGS_OPEN'
export const SET_INSTALLATION_DIRECTORY = 'SET_INSTALLATION_DIRECTORY'
export const SET_AUTO_LOAD_MORE         = 'SET_AUTO_LOAD_MORE'
export const SET_THEME                  = 'SET_THEME'
export const SET_FOLDER_STRUCTURE       = 'SET_FOLDER_STRUCTURE'
export const REPLAY_TUTORIAL            = 'REPLAY_TUTORIAL'

export const DOWNLOAD_SONG              = 'DOWNLOAD_SONG'
export const DELETE_SONG                = 'DELETE_SONG'
export const CHECK_DOWNLOADED_SONGS     = 'CHECK_DOWNLOADED_SONGS'

export const SET_DETAILS_OPEN           = 'SET_DETAILS_OPEN'
export const LOAD_DETAILS               = 'LOAD_DETAILS'
export const CLEAR_DETAILS              = 'CLEAR_DETAILS'
export const SET_DETAILS_LOADING        = 'SET_DETAILS_LOADING'

export const SET_SEARCH_SOURCES         = 'SET_SEARCH_SOURCES'
export const SUBMIT_SEARCH              = 'SUBMIT_SEARCH'

export const SET_QUEUE_OPEN             = 'SET_QUEUE_OPEN'
export const ADD_TO_QUEUE               = 'ADD_TO_QUEUE'
export const REMOVE_FROM_QUEUE          = 'REMOVE_FROM_QUEUE'
export const CLEAR_QUEUE                = 'CLEAR_QUEUE'
export const UPDATE_PROGRESS            = 'UPDATE_PROGRESS'