export const LIBRARY = {
  SONGS: 'LIBRARY_SONGS',
  PLAYLISTS: 'LIBRARY_PLAYLISTS',
  MODS: {
    ALL: 'LIBRARY_MODS_ALL',
    ACTIVATED: 'LIBRARY_MODS_ACTIVATED',
    CONFLICTS: 'LIBRARY_MODS_CONFLLICTS'
  }
}

export const BEATSAVER = {
  NEW_SONGS: 'BEATSAVER_NEW_SONGS',
  TOP_FINISHED_SONGS: 'BEATSAVER_TOP_FINISHED_SONGS',
  TOP_DOWNLOADED_SONGS: 'BEATSAVER_TOP_DOWNLOADED_SONGS'
}

export const BEATMODS = {
  NEW_MODS: 'BEATMODS_NEW_MODS',
  RECOMMENDED_MODS: 'BEATMODS_RECCOMENDED_MODS',
  APPROVED_MODS: 'BEATMODS_APPROVED_MODS',
  MOD_CATEGORIES: 'BEATMODS_MOD_CATEGORIES',
  MOD_CATEGORY_SELECT: 'BEATMODS_MOD_CATEGORY_SELECT'
}