export const SONG_NAME        = 'songName'
export const AUTHOR_NAME      = 'authorName'
export const BEATS_PER_MINUTE = 'beatsPerMinute'
export const DIFFICULTY       = 'difficultyLevels'
export const ASC              = 'asc'
export const DESC             = 'des'