export const WELCOME          = 'WELCOME'
export const SONG_LIST        = 'SONG_LIST'
export const SONG_DETAILS     = 'SONG_DETAILS'
export const PLAYLIST_LIST    = 'PLAYLIST_LIST'
export const PLAYLIST_DETAILS = 'PLAYLIST_DETAILS'
export const MODS_VIEW        = 'MODS_VIEW'
export const MOD_DETAILS      = 'MOD_DETAILS'
export const SETTINGS         = 'SETTINGS'
export const SEARCH           = 'SEARCH'
export const DONATE           = 'DONATE'
export const DIAGNOSTICS      = 'DIAGNOSTICS'
export const DOWNLOADS        = 'DOWNLOADS'

export const LIST             = 'list'
export const COMPACT_LIST     = 'compact-list'
export const GRID             = 'grid'